#!/usr/bin/env bash
#This script transfer a file from the client (my computer) to the server over the internet

#Accept 4 parameters
if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

file_path=$1
Server_ip=$2
user=$3
ssh_key=$4

scp -i "$ssh_key" -o StrictHostKeyChecking=no "$file_path" "$user@$Server_ip:~/"
