#!/usr/bin/env bash
#This script installs nginx on my web-01 server and configures a page containing "Holberton School"

set -e

export DEBIAN_FRONTEND=noninteractive

apt-get -y update
apt-get -y install nginx

mkdir -p /var/www/html
echo "Holberton School for the win!" > /var/www/html/index.html

rm -f /var/www/html/index.nginx-debian.html || true

if pgrep -x nginx >/dev/null; then
  service nginx reload
else
  service nginx start
fi
