#!/usr/bin/env bash
# Installs nginx and configures a custom 404 page

set -e
export debian_frontend=noninteractive

apt-get -y update
apt-get -y install nginx

echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

default_site="/etc/nginx/sites-available/default"

sed -i '/error_page 404/d' "$DEFAULT_SITE"

sed -i '/server_name _;/a\\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}' "$default_site"

echo "Holberton School" > /var/www/html/index.html

if pgrep -x nginx >/dev/null 2>&1; then
  service nginx reload
else
  service nginx start
fi
